POST http://localhost:3008/books
Content-Type: application/json

{
  "title": "Captain Nemo",
  "year": 1957,
  "author_id": 2
}

####
GET http://localhost:3008/books-count

####
####
GET http://localhost:3008/books-authors

####
GET http://localhost:3008/books

####
GET http://localhost:3008/users

####

POST http://localhost:3008/register
Content-Type: application/json

{
  "email": "jess@bond.com",
  "password": "123456"
}

####

POST http://localhost:3008/login
Content-Type: application/json

{
  "email": "jess@bond.com",
  "password": "123456"
}

### 

{
  "email": "Jill@Crown.lt",
  "password": "secret1234"
}